[project]
name = "nnzero2hero"
version = "0.1.0"
description = "Karpathy NN lectures stuff"
readme = "README.md"
authors = [
    { name = "57Ajay", email = "57ajay.u@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "torch>=2.14.0",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cpu"

