pub const SPLIT_GPT2: &[(&str, &[&str])] = &[
    ("Hello've world123 how's are you!!!?", &["Hello", "'ve", " world", "123", " how", "'s", " are", " you", "!!!?"]),
    ("   spaces   everywhere   ", &["  ", " spaces", "  ", " everywhere", "   "]),
    ("x\n\ny  \t z", &["x", "\n", "\n", "y", "  \t", " z"]),
    ("こんにちは world こんにちは123", &["こんにちは", " world", " こんにちは", "123"]),
    ("1234567 12 1 123456", &["1234567", " 12", " 1", " 123456"]),
    ("don't DON'T Don'T d'LL", &["don", "'t", " DON", "'", "T", " Don", "'", "T", " d", "'", "LL"]),
    ("«word» $5.99 C++!!", &["«", "word", "»", " $", "5", ".", "99", " C", "++!!"]),
    ("\r\n\r\n hi \r\n", &["\r\n\r\n", " hi", " \r\n"]),
    ("a'b'll c've'd", &["a", "'", "b", "'ll", " c", "'ve", "'d"]),
    ("😀😀  ok", &["😀😀", " ", " ok"]),
    ("word ", &["word", " "]),
    ("word  ", &["word", "  "]),
    ("e.g. i.e.?! ...", &["e", ".", "g", ".", " i", ".", "e", ".?!", " ..."]),
    ("snake_case-kebab tail\t", &["snake", "_", "case", "-", "kebab", " tail", "\t"]),
    ("'", &["'"]),
    (" '", &[" '"]),
    ("5'll 'lless've", &["5", "'ll", " '", "lless", "'ve"]),
];

pub const SPLIT_GPT4: &[(&str, &[&str])] = &[
    ("Hello've world123 how's are you!!!?", &["Hello", "'ve", " world", "123", " how", "'s", " are", " you", "!!!?"]),
    ("   spaces   everywhere   ", &["  ", " spaces", "  ", " everywhere", "   "]),
    ("x\n\ny  \t z", &["x", "\n\n", "y", "  \t", " z"]),
    ("こんにちは world こんにちは123", &["こんにちは", " world", " こんにちは", "123"]),
    ("1234567 12 1 123456", &["123", "456", "7", " ", "12", " ", "1", " ", "123", "456"]),
    ("don't DON'T Don'T d'LL", &["don", "'t", " DON", "'T", " Don", "'T", " d", "'LL"]),
    ("«word» $5.99 C++!!", &["«word", "»", " $", "5", ".", "99", " C", "++!!"]),
    ("\r\n\r\n hi \r\n", &["\r\n\r\n", " hi", " \r\n"]),
    ("a'b'll c've'd", &["a", "'b", "'ll", " c", "'ve", "'d"]),
    ("😀😀  ok", &["😀😀", " ", " ok"]),
    ("word ", &["word", " "]),
    ("word  ", &["word", "  "]),
    ("e.g. i.e.?! ...", &["e", ".g", ".", " i", ".e", ".?!", " ..."]),
    ("snake_case-kebab tail\t", &["snake", "_case", "-kebab", " tail", "\t"]),
    ("'", &["'"]),
    (" '", &[" '"]),
    ("5'll 'lless've", &["5", "'ll", " '", "lless", "'ve"]),
];
